### ISSUE TITLE
Drop Tensorpack Dependencies

### ISSUE THREAD

**Issue by gngdb** [BayesWatch/sequential-imagenet-dataloader#1]
This can all probably be done much more succintly just wrangling the LMDB database directly:

* https://discuss.pytorch.org/t/whats-the-best-way-to-load-large-data/2977
* http://deepdish.io/2015/04/28/creating-lmdb-in-python/

**Comment by asanakoy** [comment]
Probably not, if you don't want to reimplement queues from tensorpack.

**Comment by gngdb** [comment]
Tensorpack moved dataflows into their own repo so I was technically able to remove tensorpack as a dependency in favour of tensorpack/dataflow.
