### ISSUE TITLE
a bug in preprocess_sequential.py

### ISSUE THREAD

**Issue by askerlee** [BayesWatch/sequential-imagenet-dataloader#2]
`            for fname, label in super(BinaryILSVRC12, self).get_data():
`
reports error: 
`RuntimeError: maximum recursion depth exceeded while calling a Python object`
I've checked the code of tensorpack and seems there's no "get_data()" anymore? Instead there's an `__iter__()` that returns the (fname, label) pair.

So changing it as below fixes the error:
`            for fname, label in super(BinaryILSVRC12, self).__iter__():
`

**Comment by charlesjiangxm** [comment]
Me too, this works for me

**Comment by Juicechen95** [comment]
this works to me ,too

**Comment by hongyx11** [comment]
I also found this bug.

**Comment by gngdb** [comment]
Merged this change, thanks!
