### ISSUE TITLE
At first very fast, but it get slower and slower

### ISSUE THREAD

**Issue by Juicechen95** [BayesWatch/sequential-imagenet-dataloader#5]
At the beginning, it is very fast. Less than 1s for a batch(256).

But it soon getting slower and slower. It is about 10s for a batch(256) after several epochs, which even slower than the original Pytorch dataLoader. The CPU-util is much lower than that of the begging.

Why does this happen, how can I fix it?

**Comment by ZHUANGHP** [comment]
Hi, have you figured out why this happened?

**Comment by Juicechen95** [comment]
> Hi, have you figured out why this happened?

sorry I don't... I am no longer doing that job now
