### ISSUE TITLE
how you set your environment variable

### ISSUE THREAD

**Issue by tianwen0110** [BayesWatch/sequential-imagenet-dataloader#6]
thanks for your suggestion to install tensorpack, but I meet a question. After I install tensorpack, there is also a warning :Env var $TENSORPACK_DATASET not set. how do you set your environment vairable TENSORPACK_DATASET and IMAGENET?

**Comment by ZHUANGHP** [comment]
met the same problem. Have you solved it?

**Comment by gngdb** [comment]
I've removed the environment variables so now these things are all specified in command line arguments, have a look at the changes in the README.
