### ISSUE TITLE
the master tensorpack didn't have dftools

### ISSUE THREAD

**Issue by ImMrMa** [BayesWatch/sequential-imagenet-dataloader#7]
Are there any other way to solve it?

**Comment by yogeshbalaji** [comment]
I think it doesn't work with the latest version of tensorpack. I am using tensorpack 0.8.7 and it seems to work.

**Comment by toosi** [comment]
I used `LMDBSerializer.save` instead of `dftools.dump_dataflow_to_lmdb` and it seems to work fine

**Comment by gngdb** [comment]
Updated to remove tensorpack as a dependency and specify dataflow version.
