### ISSUE TITLE
Still the same as pytorch dataloader

### ISSUE THREAD

**Issue by ZHUANGHP** [BayesWatch/sequential-imagenet-dataloader#8]
I tried to run the imagenet_seq/data.py to test the loading speed.  It shows around 1.4 its/s and 1.6 s/it for batch size 128 and 256 respectively. However, the pytorch dataloader can give me the same numbers. I am runing ubuntu with an RTX 2080 Ti.

**Comment by gngdb** [comment]
Sorry I don't know what might have caused that problem. I've made some changes to update the code in line with changes to tensorpack's dataflow. You might be able to figure out what's going wrong looking at the example Imagenet script I've added and the details in the wandb logs when I ran the benchmark experiment: https://wandb.ai/gngdb/trial-imagenet/runs/3gcmoq0j
