### ISSUE TITLE
tensorpack version

### ISSUE THREAD

**Issue by lusinlu** [BayesWatch/sequential-imagenet-dataloader#9]
Thanks for the good project. Could you please mention the version of the tensorpack with which the project is compatible. As the last versions of the tensorpack don't have 'LMDBDataPoint'.

**Comment by gngdb** [comment]
I've removed tensorpack as a dependency to use tensorpack/dataflow instead and I put the specific version of the git repo I installed for tensorpack/dataflow so it should be replicable. Also, all the versions of all the packages used are in the wandb logs for the benchmark experiment: https://wandb.ai/gngdb/trial-imagenet/runs/3gcmoq0j/files/conda-environment.yaml
